# Generated by Django 4.2.2 on 2023-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='incorrect_answers',
            field=models.IntegerField(default=0),
        ),
    ]
